# fly.toml app configuration file generated for api-aluno-ifce-crato on 2023-08-06T12:09:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-aluno-ifce-crato"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
