# fly.toml app configuration file generated for api-aluno-ifce-crato on 2023-08-06T12:09:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-aluno-ifce-crato"
primary_region = "gru"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = [ "app" ]
